apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}
  type: {{ .Values.mysql.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          envFrom:
            - secretRef:
                name: {{ .Values.mysql.secretName }}
          ports:
            - containerPort: {{ .Values.mysql.containerPort }}
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
