apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server.name }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.server.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.name }}
    spec:
      containers:
        - name: {{ .Values.server.name }}
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.service.name }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: {{ .Values.server.name }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      nodePort: {{ .Values.server.service.nodePort }}
